---
title: 'Assessing the risks and opportunities of major transport infrastructure projects for active travel: a geographical approach'
author: "Robin Lovelace"
date: "`r Sys.Date()`"
output: bookdown::html_document2
bibliography: documents/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F)
pkgs = c("sp", "tmap", "rgeos", "stplanr")
lapply(pkgs, library, character.only = T)
```

# Abstract {-}

The impacts of major infrastrucuture pojects on many aspects of life are well established. However, the impacts on other modes of travel, particularly walking and cycling, have been under-explored. The paper sets out to fill this research gap, using Geographic Information Systems (GIS). The method is developed in theoretical terms, focussing on risks of 'severance' and opportunities associated with active travel 'desire lines' that run parallel to proposed routes. Then it is applied to a large scale case study: the planned construction of a high-speed rail network on the UK (HS2). This empirical case study demonstrates that the method is scalable yet able to identify risks and opportunites at local levels, down to road segments, which could guide pro-cycling interventions associated with construction or provide a source of evidence to re-assess the overall impacts of major infrastructure projects.

# Introduction

Major transport infrastructure projects are a major beneficiary of largescale investment of public funding across the world. There are many reasons for this, the primary being that they are seen as an 'engine for growth', stimulating regional economic integration and the increased specialisation of labour due to the reduction in travel times. Secondary benefits are seen to include the reduction of geographical inequalities between core and peripheral regions; econonimic saving via reduced costs for trips that are taking place already; and improved 'quality of life' for people who would be enabled to visit friends and family. In some cases, environmental arguments have been made for investment in transport infrastructure, despite the finding that increased transport connectivity tends to increase demand. In practice, psychological factors may play an important role in explaining preferences for expenditure on major infrastructure in general, rather than revenue expenditure, e.g. on research and education which could boost economic growth through technological development and a more productive workforce.

Regardless of the diverse motivations for transport infrastructure investment, it is clear that they have, and will continue to have, major impacts: economic, social and environmental. It is therefore unsurprising that there is a substantial body of literature dedicated to the evaluation of the impacts of major infrastructure, which can be considered a sub-discipline in the field of transport studies in its own right. In parallel to such research programs there has been growing interest from transport researchers in the impacts of major infrastructure projects on transport patterns overall (going beyond the question of utilisation of the transport service provided by the specific piece of new infrastructure).

Active transport lies at the opposite end of the spectrum of transport investment. Interventions that increase 'walkability' and 'cyclability' are usually (but not always or necessarily) smaller, cheaper and less disruptive than major infrastructure. They are often localised. They are often the responsibility of local transport authorities, whereas major infrastructure projects are almost always overseen by national transport departments or dedicated organisations reporting directly to central government.

The lack of organisational overlap between major transport infrastructure and active travel interventions helps explain why the two are seldom considered. There has been very little research into the active travel impacts of major infrastructure projects. Yet, as we shall see in the next section, major transport infrastructure has the potential to have a wide range of impacts on transport behaviour overall and levels of active travel in particular. The purpose of this paper is to create a framework for the consideration of active travel impacts of major transport infrastructure. More importantly from a practitioner perspective, it outlines and demonstrates methods for assessing these impacts and prioritising interventions that will reduce the negative impacts on walking and cycling. The most radical option to minimise the active transport impacts of building large roads and railways etc is not to build them at all, and invest in a series of smaller walking and cycling interventions instead. Arguments for doing this are discussed in the final section.

# A typology of active transport impacts of major transport infrastructure projects



# Methods for assessing the impacts of major infrastructure projects: a review



# A typology of 

# Method

# Case studies

<!-- ## The impacts of high speed rail on cycling in the UK -->

<!-- To assess the potential benefits of new crossings for cycling uptake during and after construction of HS2, the method was applied to geographical data about the route and current travel patterns surrounding it. The first stage was to identify all commutes that could potentially be directly affected by the HS2 infrastructure, by selecting all commuter desire lines that pass anywhere within a 20 km buffer. This is illustrated in Figure xx. -->

<!-- ```{r} -->
<!-- hs2 = readRDS("input-data/hs2.Rds") -->
<!-- l = readRDS("input-data/l_mini.Rds") -->
<!-- proj4string(hs2) = proj4string(l) -->
<!-- hs2_buf20 = stplanr::buff_geo(hs2, 20000) -->
<!-- # l = readRDS("../pct-bigdata/pct_lines_oneway_shapes.Rds") -->
<!-- l_sev = l[hs2,] -->
<!-- l_sam = l[sample(nrow(l), 1000),] # work with sample (comment for all) -->
<!-- # osm_tiles = read_osm(bb(hs2, ext = 1.2)) -->
<!-- # saveRDS(osm_tiles, "input-data/osm_tiles_hs2.Rds") -->
<!-- l_buf = l[hs2_buf20,] -->
<!-- osm_tiles = readRDS("input-data/osm_tiles_hs2.Rds") -->
<!-- qtm(osm_tiles) + -->
<!--   qtm(l_buf, line.col = "blue") + -->
<!--   qtm(hs2, line.col = "black", line.lwd = 3) + -->
<!--   tm_shape(hs2_buf20) + -->
<!--   tm_borders(lwd = 4) -->
<!-- # select lines that cross the route -->

<!-- ``` -->

###  Cycling potential along the the HS2 route

The section between Sheffield and Rotherham, for example, has relatively high cycling potential.

<!-- ### Opportunities to reduce severance -->


<!-- ```{r, fig.cap="Overview of the proposed HS2 route, overlaid with a sample of commute desire lines (grey) and all desire lines that cross the proposed route."} -->

<!-- osm_tiles = readRDS("input-data/osm_tiles_hs2.Rds") -->
<!-- qtm(osm_tiles) + -->
<!--   qtm(hs2, line.col = "black", line.lwd = 3) + -->
<!--   qtm(l_sam, line.col = "blue") + -->
<!--   qtm(l_sev) -->
<!-- # select lines that cross the route -->
<!-- ``` -->


# Discussion

# References

Ideas:
<!-- Use a regression mode of distance to transport infrastructure to estimate deterrant of motorways - and therefore how it could be mitigated. Outliers with high cycling relative to road proximity could show how to mitigat negative impact. -->