# Be Curious public engagement event, 17th March 2017

Title of your activity *

Prioritising Cycling Infrastructure in Leeds

Up to 10 words
Description of your activity *

This activity will give the public a unique and interactive insight into the high-impact and international research into sustainable transport being led by the University of Leeds.
It will guide attendees through a scenario whereby they design a sustainable transport system in the city, with an emphasis on cycling infrastructure.
After developing their vision of the future attendees will be encouraged to see how this could scale internationally.
Results will be saved on-line and disseminated for future engagement, using the on-line code sharing website GitHub.
Options range from new 'cycle superhighways' and junctions redesigned for safety to simple measures like new cycle parking points.
The Department for Transport funded Cycling Infrastructure Prioritisation Toolkit (CyIPT) will make these visions come to life, in an interactive map that you will be able to save for future reference.
The activity will give attendees early access to the CyIPT, developed by researchers at the University of Leeds' Institute for Transport Studies (ITS).

Aimed at the public audience making a clear link to the theme 'We are International' (up to 50 words)

This activity will put you in control of Leeds' investment in cycling infrastructure up to 2050.
You will be able to decide what is built, where to put it, and how to prioritise this investment.
In the process you'll learn how evidence can help prioritise investment for a 'zero carbon' future internationally.
<!-- Options range from new 'cycle superhighways' and junctions redesigned for safety to simple measures like new cycle parking points. -->


Format of your activity *
Table top activity
Tour
Talk
Other:
Timing of your activity
We hope all activities would be available for the duration of the event (10-4). If your activity has some specific requirements of start/finish times, please detail them below.
Is your activity suitable for all age groups? *
Yes
No
If you clicked no, please give details.
How many people will be involved in delivering your activity on the day? *
Logistics: Do you require power? If so, how many sockets? *
Logistics: Do you require tables and chairs? If so, how many? *
Logistics: Do you require a poster board? If so, please be advised that conference posters aimed at an academic audience are not usually well received. What the poster board is useful for is displaying images. *
Logistics: Do you require extra space around your table? If so, approx. how much? *
Logistics: We expect stall holders to provide all equipment (and ensure electrical equipment is PAT tested), if there is anything extra you require us to source please detail below and we will get back to you whether this is possible *
Logistics: Any further requests not covered in the above?
Which category of engagement does your activity sit within? You can select more than one. *
Dissemination of research outcomes
Development of research ideas
Co-Production of research (the public will be involved in the research on the day)
Never submit passwords through Google Forms.
This content is neither created nor endorsed by Google. Report Abuse - Terms of Service - Additional Terms
Google Forms

## More blurb


Be Curious 2018: We are International Stage 2 application form
Please complete the following form as fully as possible for your proposed activity for Be Curious 2018. We need this information to allocate space for your activity, and also to be able to effectively promote the event and put together the programme. The deadline for submission on the completed form is Monday 4th December 2017. By completing this form you are committing to providing this activity for Be Curious 2018 on Saturday 17th March 2018.

Once submitted, further information maybe requested and a risk assessment of your activity will be required before we can fully accept your activity. Details of the risk assessment will be circulated in the new year. To note, funding for your activities at Be Curious should come from your research grants or an alternative source. We are not contributing to funding these activities. We will however aim to provide you the required space, tables, chairs, electrics and poster boards alongside a sandwich lunch for all staff/student volunteers
*Required
Lead Name *
Name of the person who is leading on the activity; this person will have to be present at the event on Saturday 17th March
Lead contact email address *
Lead contact phone number (which can be used on the day of the event) *
