---
title: "Propensity to Cycle Hackathon"
author: "Robin Lovelace"
date: "January 14, 2016"
output:
  word_document: default
  html_document: default
---

## Description

This Propensity to Cycle Tool Hackathon is designed for advanced users and developers of the tool to share ideas, use-cases and skills. The aim is to build know-how of the tool and how it can be used, modified and extended to improve its ability to help provide an accessible evidence-based for transport planning.

Attendees will likely split into teams at the outset to work on issues such as:

- How to best make use of data generated by the PCT
- New scenarios (e.g. 'Go York')
- Modifications to the PCT user interface
- Extensions to the PCT (e.g. rail or cycle parking)
- Modification to the code (e.g. refactor for database, sf support or conversion of stata code to R)

It is hoped that the knowledge learned will be shared beyond the event via write-ups, workshops and extensions to the PCT by attendees.

## Prerequisites

R must be installed, in addition to the development version of the stplanr package: https://github.com/ropensci/stplanr

It will help if you have Git installed on your computer.
With it installed the following commands will download all files you need to reproduce the tool:

```{r, engine='bash', eval=FALSE}
# clone the pct data creation scripts
git clone git@github.com:npct/pct-demo
```

If you want to work on the 'full' PCT you'll need these on your laptop before the hackathon.

To download the input data, install git lfs from [GitHub](https://git-lfs.github.com/) and run the following lines of code from an appropriate shell (e.g. bash on Linux or Windows Powershell):

```bash
git lfs install # check lfs is working
# clone the data (warning - large)
git clone git@github.com:npct/pct-inputs.git # raw input files
git clone git@github.com:npct/pct-outputs-national.git # national outputs
git clone git@github.com:npct/pct-outputs-regional-R.git # regional outputs used by pct-shiny
```

The contents of the regional outputs are used by the code in pct-shiny, which can be downloaded with:

```bash
git clone git@github.com:npct/pct-shiny.git 
```

## Agenda

See full draft agenda here: https://github.com/npct/pct/blob/master/minidocs/pct-hackathon.Rmd

The rough running order of the event will be as follows:

### Getting up to speed 9:00-10AM (optional)

The aim of this section is familiarise attendees with the PCT. Optional for experienced users.

- Policy relevance and the type of questions we want to answer (15 minutes)

- Open question and answer and a chance for people to ask technical questions (15 minutes)

- Meet and greet and team formation - talk to person next to you and decide what you want to get out of it (15 minutes over coffee) 

- Coffee break, discussion and set-up (15 minutes)

### Learning to use and hack the PCT (10 - 12)

- Live demo and where we're at with the Propensity to Cycle Project and quick demo (Robin - 15 minutes)

The aim of this section is to learn skills needed for the hackathon. By the end of it everyone should be in a team with a plan.

- Split session. Getting up to speed with the tool - Robin, Nikolai and Ali to do tech explanation for people with PCT installed, others to demonstrate use cases for people without (45 minutes)

- Free time to play with the tool, test hacks and network to finalise teams (1 hr)

**Lunch: 12 - 1PM**

### The hackathon (1 - 4pm)

This is where the bulk of the work will take place

- Reconvene to hear and discuss team ideas (30 minutes, ~5 min per team)

- Free time for hackathon (2 hrs)

### Feedback (4 - 4:30PM)

- Presentation of hacks and discussion


